### PR TITLE
Fix issue with ‘Object not found’ errors

### PR DESCRIPTION
**Pull request by kricha**
Fix issue with ‘Object not found’ errors on insert or variances data on update

### CODE REVIEW

**Comment by kricha** [comment]
@makasim review and merge please, this is important for production :)

**Comment by makasim** [comment]
I dont think sleep is the right solution to the problem. So it is unlikely to be merged as is.

We should find a real problem and provide a solution for it.

**Comment by kricha** [comment]
@makasim this pr gives a way at least somehow to solve a problem. Also it didn't break default process, because of sleep(0) as default.

By the way, I think that the database simply does not have time to write changes or new entries.

**Comment by kricha** [comment]
Close for now.

**Pull request closed without merging**
